apiVersion: apps/v1
kind: Deployment
metadata:
  name: clay-etcd-controller
  namespace: kstone
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: clay-etcd-controller
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: clay-etcd-controller
    spec:
      containers:
      - args:
        - etcdcluster
        command:
        - /manager
        image: wangzhichidocker/etcd-operator:v0.2.3
        imagePullPolicy: IfNotPresent
        name: clay-etcd-controller
        resources:
          limits:
            cpu: "2"
            memory: 4G
          requests:
            cpu: "2"
            memory: 4G
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: kstone
      serviceAccountName: kstone
      terminationGracePeriodSeconds: 30