apiVersion: v1
kind: Service
metadata:
  labels:
    app: inspection-controller
  name: clay-inspection-controller
  namespace: kstone
spec:
  ports:
  - name: http
    port: 80
    targetPort: 9090
  selector:
    app.kubernetes.io/name: clay-inspection-controller