apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: monitoring
  name: kstone-inspection-controller
  namespace: cattle-prometheus
spec:
  endpoints:
  - port: http
  namespaceSelector:
    matchNames:
    - kstone
  selector:
    matchLabels:
      app: inspection-controller